spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/uar
    username: postgres
    password: example
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: ca.uhn.fhir.jpa.model.dialect.HapiFhirPostgresDialect
        search:
          enabled: false